# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar


exec-once = awww-daemon
exec-once = awww img ~/Pictures/Wallpapers/danbo.jpg

# Authentifizierung (KDE Agent)
#exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Benachrichtigungen (Mako)
exec-once = mako

# Clipboard History (Cliphist)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Portals (Sicherstellen, dass sie korrekt starten)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = hyprctl dispatch focusmonitor DP-2

exec-once = elephant
exec-once = todoist s

exec-once = [workspace 1 silent] kitty --class neovim-init -e nvim
exec-once = [workspace 2 silent] kitty
exec-once = [workspace 3 silent] firefox
exec-once = [workspace 4 silent] spotify
exec-once = [workspace 5 silent] kitty -e /home/digi/.cargo/bin/ratatoist

