# --- Hyprland Haupt-Config ---


# 8. Autostart (Dienste)
source = ~/.config/hypr/autostart.conf

# 1. Variablen & Programme
source = ~/.config/hypr/programs.conf

# 2. NVIDIA & System-Umgebung
source = ~/.config/hypr/env.conf

# 3. Monitore
source = ~/.config/hypr/monitors.conf

# 4. Aussehen (Farben, Animationen, Blur)
source = ~/.config/hypr/appearance.conf

# 5. Eingabe (Tastatur, Maus)
source = ~/.config/hypr/input.conf

# 6. Tastenkürzel (Keybinds)
source = ~/.config/hypr/keybinds.conf

# 7. Fenster-Regeln
source = ~/.config/hypr/windowrules.conf

